### ISSUE TITLE
Activity instructions

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/git-intro-activity#10]
Under Basic Commands: https://github.com/StoneyJackson/git-intro-activity/blob/master/activity.md#basic-commands, next to movies.txt, I would like to modify the instructions that say: "Put the last movie each of you watched" to say "Put the last movie each of you watched in alphabetical order". 

The instructions that appear later: https://github.com/StoneyJackson/git-intro-activity/blob/master/activity.md#stagecacheindex indicate that they should put them in "reverse alphabetical order". What if they are already in reverse alphabetical order?

**Comment by StoneyJackson** [comment]
Good idea. Thanks!
