### ISSUE TITLE
Trouble with participants using Windows command prompt

### ISSUE THREAD

**Issue by StoneyJackson** [StoneyJackson/git-intro-activity#3]
I'm not sure if the activity mentions this or not, but the commands all assume a bash prompt with some basic tools like vim. I think the git install comes with a bash prompt, so we should probably tell participants to use that and not their command prompt. Or they'll need to make appropriate adjustments (e.g., all / become ) as they go along.

**Comment by burdged** [comment]
In Windows you can usually use the forward slash. I didn't have any issues with the activity until we added the instructions to:  mkdir PATH_TO_SOME_LOCATION/git-repo (this instruction requires the use of a backslash).

I'd suggest that we change the instructions asking them to navigate to the folder where they want to create their repo using cd. Then the instructions can simply say:  mkdir git-repo OR we could include a note in this section that they will have to use a backslash when creating the git-repo folder, for example:

mkdir PATH_TO_SOME_LOCATION/git-repo [Windows users must use a backslash here]

Thoughts?
