### ISSUE TITLE
Use of slides

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/git-intro-activity#6]
Should we use only the slides on github and not have any slides in the dropbox folder?

**Comment by kussmaul** [comment]
Not sure. :-) It is a bit annoying to open a presentation and find that it's just a pointer to something else, but it's nice having one place (currently Dropbox) with the slides for every session, Could we have another master list of the materials - maybe a wiki or GDoc page that links to Dropbox, Drive, GitHub, etc?
I think it looks more professional when the POSSE materials have a consistent appearance, which gets harder as we use more different file formats.

**Comment by StoneyJackson** [comment]
We decided that this is a change to POSSE, and not this project/activity. So I'm closing this.
