### ISSUE TITLE
git log

### ISSUE THREAD

**Issue by burdged** [StoneyJackson/git-intro-activity#8]
Regarding the activity: https://github.com/StoneyJackson/git-intro-activity/blob/master/activity.md

I would like to suggest that we move the question "What does git log do?" to later in the activity, in particular after it has been used the second time. If only one commit has been made, how do you know that it will show all commits? That they are in reverse chronological order, etc... 
How about moving it after:
3. If you want to write a more detailed commit message (which is good practice) what command would you use?

**Comment by StoneyJackson** [comment]
I like! Change made.
